version: "3.8"

services:
  app:
    container_name: parking_app_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    restart: always
  db:
    container_name: parking_db
    image: postgres:16
    restart: always
    ports:
      - "2010:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data_parking:/var/lib/postgresql/data
volumes:
  db_data_parking:
