version: "3.8"

services:
  db:
    container_name: parking_db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_parking:/var/lib/postgresql/data
volumes:
  db_data_parking: